#version 460
#extension GL_EXT_buffer_reference2 : require
#extension GL_EXT_ray_tracing : enable
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_int64 : require

#include "constants.glsl"
#include "raycommon.glsl"
#include "push_constants.glsl"
#include "types.glsl"

layout(location = 0) rayPayloadEXT MousepickPayload mousepickPayload;

layout(push_constant, scalar) uniform PushConstants { MousePickPushConstant data; } pushConstant;

layout(buffer_reference, scalar) readonly buffer CameraDataBuffer { CameraData data; };
layout(buffer_reference, scalar, buffer_reference_align = 4) buffer MousePickBuffer { uint data[]; };

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;

void main() {	
    CameraData camera = CameraDataBuffer(pushConstant.data.cameraDeviceAddress).data;
    MousePickBuffer mousePick = MousePickBuffer(pushConstant.data.mousePickBufferAddress);

    const vec2 pixelCenter = vec2(gl_LaunchIDEXT.xy) + vec2(0.5);
    const vec2 inUV = pixelCenter/vec2(gl_LaunchSizeEXT.xy);
    vec2 d = inUV * 2.0 - 1.0;	
    
    vec4 origin = camera.viewInverse * vec4(0,0,0,1);
    vec4 target = camera.projInverse * vec4(d.x, d.y, 1, 1) ;		
    vec4 direction = camera.viewInverse*vec4(normalize(target.xyz / target.w), 0);	

    uint rayFlags = gl_RayFlagsOpaqueEXT | gl_RayFlagsCullFrontFacingTrianglesEXT;
    uint cullMask = 0xff;
    float tmin = 0.001;
    float tmax = 10000.0;

    traceRayEXT(topLevelAS, rayFlags, cullMask, 0, 0, 0, origin.xyz, tmin, direction.xyz, tmax, 0);

    mousePick.data[0] = mousepickPayload.instanceIndex;
    mousePick.data[1] = mousepickPayload.primitiveIndex;
}





