#pragma once

constexpr unsigned int FRAME_OVERLAP = 2;

#define UNDEFINED_STRING "UNDEFINED_STRING"

#define PRESENT_WIDTH 512
#define PRESENT_HEIGHT 288

#define LAPTOP_DISPLAY_WIDTH 640
#define LAPTOP_DISPLAY_HEIGHT 430

#define HOUSE_BEDROOM_Z_MIN -1.8f
#define HOUSE_BEDROOM_Z_MAX 1.8f
#define HOUSE_BEDROOM_X_MIN -2.75f
#define HOUSE_BEDROOM_X_MAX 1.6f

#define HOUSE_BATHROOM_X_MIN -2.715f
#define HOUSE_BATHROOM_X_MAX -0.76f
#define HOUSE_BATHROOM_Z_MIN 1.9f
#define HOUSE_BATHROOM_Z_MAX 3.8f

#define HOUSE_BATHROOM_DOOR_X -1.6f
#define HOUSE_HALL_DOOR_X 0.5f

#define DOOR_WIDTH 0.9